on:
  push:
    branches:
      - main

name: Create Release

jobs:
  build:
    name: Create Release
    steps:
      - name: Create Release
        id: create_release
        uses: zendesk/action-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
